version: '3.4'

services:
    php:
        build: .
        image: docteurklein/xhprof-analyze
        depends_on:
            - neo4j
        stdin_open: true
        tty: false

    neo4j:
        image: neo4j
